//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHLK22CNT3Lesson11_2210900037.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhmCategory
    {
        public int NhmId { get; set; }
        public string NhmCateName { get; set; }
        public Nullable<bool> NhmStatus { get; set; }
    }
}
